# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/id_grupo_05',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/id_grupo_05',
                'lib_path': 'id_grupo_05'},
  'syms': {'id_grupo_05.core': {'id_grupo_05.core.foo': ('core.html#foo', 'id_grupo_05/core.py')}}}
