# Autogenerated by nbdev

d = { 'settings': {'branch': 'a', 'doc_baseurl': '/a', 'doc_host': 'https://a.github.io', 'git_url': 'https://github.com/a/a', 'lib_path': 'a'},
  'syms': {'a.core': {'a.core.foo': ('core.html#foo', 'a/core.py')}}}
