---
title: "Bienvenida a la Aplicación de Sumas con los Dedos"
format: html
---

## Decripción del problema

Muchos padres no disponen del tiempo o la energía suficiente para jugar con sus hijos, lo que lleva a que los niños pequeños pasen largas horas frente a pantallas. Aunque los videos educativos a los que están expuestos pueden ser adecuados para su edad, a menudo carecen de suficiente interactividad, lo que afecta negativamente el aprendizaje de habilidades como la pronunciación de palabras o la comprensión de conceptos matemáticos.

El objetivo de este proyecto es desarrollar una aplicación que ofrezca retroalimentación interactiva en operaciones matemáticas como sumas, brindando a los niños una experiencia educativa más dinámica y efectiva.

## Como abordaremos el problema

Crearemos una aplicación que permitirá a los niños resolver sumas utilizando los dedos de sus manos. En la pantalla aparecerán distintas operaciones, y los niños podrán ingresar el resultado mostrando el número correcto con sus dedos. A continuación, te explicamos cómo usar la aplicación.

## Funcionalidades inteligentes

- Detección de la posición de las manos y dedos: Utilizamos el modelo de deteccion de manos de ml5 que permite de identificar y capturar las posiciones clave de las manos y los dedos. Esta funcion inteligente es la base que ocupamos para desarrollar la suma con las manos.
- Identificación de dedos doblados o rectos: Usando la detección de posiciones proporcionada por el modelo, implementamos un cálculo de distancia entre la punta y el medio de un dedo para evaluar si un dedo está doblado o recto. Esta funcion inteligente nos permite interpretar la postura de los dedos basandonos en el modelo de deteccion inicial y gracias a esto logramos hacer realidad nuestro objetivo de sumar con las manos.

## ¿Cómo funciona?

1. **Activa tu cámara**: La aplicación va a utilizar tu cámara para detectar tus manos. No te preocupes, no vamos a guardar ninguna imagen, solo necesitamos ver cuántos dedos estás levantando.

2. **Levanta tus dedos**: La aplicación podrá ver cuántos dedos de cada mano tienes levantados. Por ejemplo, si levantas 3 dedos de una mano y 2 de la otra, la aplicación sabrá que 3 + 2 es igual a 5.

3. **Mira el resultado**: Después de que la aplicación vea cuántos dedos tienes levantados, te dirá cuántos dedos has levantado en total, ¡y eso es una suma!

## ¡Pruébalo!

Levanta diferentes números de dedos y observa cómo la aplicación cuenta tus dedos para sumar. Intenta con diferentes combinaciones para practicar la suma.

> Recuerda, esta aplicación es solo una herramienta para ayudarte a aprender. ¡Diviértete sumando y sigue practicando!

## ¿Listo para empezar?

Dirígete a la siguiente página para comenzar con la aplicación de detección de manos y empieza a sumar con tus dedos: [Ir a la aplicación de sumas](suma.qmd)